name: Version Projects
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/version.yaml"
      - "src/projectA/**"
      - "src/projectB/**"
  workflow_dispatch:

jobs:
  version-projectA:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}
      version: ${{ steps.version.outputs.version }}
      major: ${{ steps.version.outputs.major }}
      minor: ${{ steps.version.outputs.minor }}
      patch: ${{ steps.version.outputs.patch }}
      changed: ${{ steps.version.outputs.changed }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          major_pattern: "(MAJOR-A)"
          minor_pattern: "(MINOR-A)"
          change_path: "src/projectA"
          namespace: "a"

  version-projectB:
    runs-on: ubuntu-latest
    outputs:
      version_tag: ${{ steps.version.outputs.version_tag }}
      version: ${{ steps.version.outputs.version }}
      major: ${{ steps.version.outputs.major }}
      minor: ${{ steps.version.outputs.minor }}
      patch: ${{ steps.version.outputs.patch }}
      changed: ${{ steps.version.outputs.changed }}
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          major_pattern: "(MAJOR-B)"
          minor_pattern: "(MINOR-B)"
          change_path: "src/projectB"
          namespace: "b"

  tag:
    runs-on: ubuntu-latest
    needs: [version-projectA, version-projectB]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create Project A Tag
        if: ${{ !env.ACT }} && ${{ needs.version-projectA.outputs.changed == 'true' }}
        run: |
          git tag -a ${{ needs.version-projectA.outputs.version_tag }} -m "Version ${{ needs.version-projectA.outputs.version_tag }}"
          git push origin ${{ needs.version-projectA.outputs.version_tag }}

      - name: Create Project B Tag
        if: ${{ !env.ACT }} && ${{ needs.version-projectB.outputs.changed == 'true' }}
        run: |
          git tag -a ${{ needs.version-projectB.outputs.version_tag }} -m "Version ${{ needs.version-projectB.outputs.version_tag }}"
          git push origin ${{ needs.version-projectB.outputs.version_tag }}

